{% set name = "urlscan" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urlscan-{{ version }}.tar.gz
  sha256: e0ec986e5aa2da57dd2face8692116d80af173d4eb56a78e4fd881731113307f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.3
    - urwid >=1.2.1
test:
  imports:
    - urlscan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/firecat53/urlscan
  summary: View/select the URLs in an email message or file
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - asford
