{% set name = "urlscan" %}
{% set version = "0.9.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urlscan-{{ version }}.tar.gz
  sha256: da66b99b3364f97d11ecfc105b8c95dd155bd08d8313dd9cc6472791493480d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.3
    - urwid >=1.2.1
test:
  imports:
    - urlscan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/firecat53/urlscan
  summary: View/select the URLs in an email message or file
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - asford
