{% set name = "urlscan" %}
{% set version = "0.9.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urlscan-{{ version }}.tar.gz
  sha256: 01d10888285390316b067d0a98e2e5aaea3fdfd85568203a2092829f19bd0a6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.3
    - urwid >=1.2.1
test:
  imports:
    - urlscan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/firecat53/urlscan
  summary: View/select the URLs in an email message or file
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - asford
